<?php
namespace cmsgears\social\meta;

// Yii Imports
use \Yii;
use yii\helpers\Url;

class SocialMeta extends \yii\base\Component {

	public $page;
	public $content;

	public $homePageSlug	= 'home';
	public $postBasePath	= 'post';

	public $twitter			= [];

	public $facebook		= [];

	// TODO: Add config to use thumb or image.

	// TODO: Use DB Config to configure all the meta tags

	// TODO: Get real FB Author details instead of global author

	public function generateMetaTags() {
		
		$metaContent	= '';

		if( isset( $this->page ) ) {
			
			$ogUrl		= null;
			$banner		= $this->content->banner;

			if( $this->page->isPost() ) {

				$ogUrl	= Url::toRoute( [ "/$this->postBasePath/$page->slug" ], true );
			}
			else {

				if( strcmp( $this->page->slug, $this->homePageSlug ) == 0 ) {

					$ogUrl	= Url::toRoute( [ '/' ], true );
				}
				else {

					$ogUrl	= Url::toRoute( [ '/$page->slug' ], true );	
				}
			}
			
			if( $this->twitter[ 'required' ] ) {
				
				$metaContent	.= $this->generateTwitterCard( $ogUrl, $banner );
			}
	
			if( $this->facebook[ 'required' ] ) {
				
				$metaContent	.= $this->generateFacebookTags( $ogUrl, $banner );
			}
			
			$metaContent	.= "<link rel='canonical' href='$ogUrl'/>";
		}

		return $metaContent;
	}
	
	/**
	 * Twitter Card - summary_large_image
	 */
	private function generateTwitterCard( $ogUrl, $banner ) {
		
		$site		= $this->twitter[ 'site' ];
		$domain		= $this->twitter[ 'domain' ];
		$creator	= $this->twitter[ 'creator' ];
		$page		= $this->page;
		$content	= $this->content;

		// TODO: Add support for all type of cards generated by Twitter
		$metaContent	= "<meta name='twitter:card' content='summary_large_image' />
							<meta name='twitter:site' content='$site' />
							<meta name='twitter:creator' content='$creator' />
							<meta name='twitter:title' content='$page->name' />
							<meta name='twitter:domain' content=$domain' />
							<meta name='twitter:description' content='$content->summary' />";

		if( isset( $banner ) ) {

			$banner			= $banner->getFileUrl();

			$metaContent	.= "<meta name='twitter:image' content='$banner' />";
		}
	
		return $metaContent;
	}

	private function generateFacebookTags( $ogUrl, $banner ) {
		
		$appId		= $this->facebook[ 'appId' ];
		$site		= $this->facebook[ 'site' ];
		$locale		= $this->facebook[ 'locale' ];
		$page		= $this->page;
		$content	= $this->content;

		$metaContent	= "<meta property='og:title' content='$page->name' />
							<meta property='og:site_name' content='$site'/>
							<meta property='og:url' content='$ogUrl' />
							<meta property='og:description' content='$content->summary'/>		
							<meta property='og:locale' content='$locale' />
							<meta property='fb:app_id' content='$appId' />";

		if( isset( $banner ) ) {

			$banner			= $banner->getFileUrl();

			$metaContent	.= "<meta property='og:image' content='$banner'>";
		}
		
		if( $this->page->isPost() ) {

			$author			= $this->facebook[ 'author' ];
			$publisher		= $this->facebook[ 'publisher' ];

			$metaContent	.= "<meta property='og:type' content='article' />
								<meta property='article:author' content='$author' />
								<meta property='article:publisher' content='$publisher' />";
		} 
		else {

			$metaContent	.= "<meta property='og:type' content='website' />";
		}

		return $metaContent;
	}
}

?>